import os

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_FROM_PHONE_NUM = os.getenv("TWILIO_FROM_PHONE_NUM")
RECIPIENT_PHONE_NUM = os.getenv("RECIPIENT_PHONE_NUM")
